"""
slickshift.browser_agent.server -- WebSocket server for the Chrome extension.

The server listens on 127.0.0.1 (loopback only -- never exposed to the LAN)
on BROWSER_AGENT_PORT. The Chrome extension background service worker connects
to ws://127.0.0.1:<port>/browser-agent when the browser starts.

Lifecycle:
    Call BrowserAgentServer.start() after QApplication is created. It spawns
    a daemon thread that owns an asyncio event loop. The server runs for the
    lifetime of the Qt process; no explicit stop is needed because the thread
    is daemonic.

    Call BrowserAgentServer.stop() in MainWindow.closeEvent() if you want a
    clean asyncio shutdown rather than relying on daemon-thread teardown.

Message format (JSON, both directions):
    Host -> Extension: { "id": <str>, "command": <str>, ...params }
    Extension -> Host: { "id": <str>, "result": <any> }
                    or { "id": <str>, "error": <str> }

The `id` field is an opaque correlation token generated by the host
(uuid4 short hex). The extension echoes it back unchanged.

Request/response flow:
    send_command(command, **params) is a thread-safe call from the Qt main
    thread (or any thread). It:
      1. Generates a message ID.
      2. Registers a threading.Event + result slot keyed on that ID.
      3. Schedules the send on the asyncio loop via call_soon_threadsafe.
      4. Blocks (with timeout) until the extension reply arrives.
      5. Returns the result or raises on error/timeout.

    This is intentionally simple and synchronous from the caller's perspective.
    For a prototype with infrequent requests (e.g. user presses a button) this
    is fine. A future version could use asyncio Futures piped back through Qt
    signals for non-blocking use.

Implementation note:
    Uses websockets.asyncio.server (websockets 14.x modern API) to avoid the
    legacy serve() deprecation warning. The handler receives a ServerConnection
    object; the request path is at websocket.request.path.
"""

from __future__ import annotations

import asyncio
import json
import logging
import threading
import uuid
from typing import Any

logger = logging.getLogger(__name__)

# Port the Chrome extension connects to. Matches background.js SLICKSHIFT_PORT.
BROWSER_AGENT_PORT: int = 8765

# Path the WebSocket server listens on. Extension connects to this path.
BROWSER_AGENT_PATH: str = "/browser-agent"

# How long send_command() waits for the extension to reply before giving up.
COMMAND_TIMEOUT_S: float = 10.0


class BrowserAgentServer:
    """
    WebSocket server that the Chrome extension connects to.

    One instance is created at startup and lives for the Qt process lifetime.
    Not thread-safe for concurrent send_command() calls targeting the same
    message ID, but prototype usage (one button press at a time) is fine.
    """

    def __init__(self) -> None:
        self._loop: asyncio.AbstractEventLoop | None = None
        self._thread: threading.Thread | None = None
        self._ws_server = None
        # Active connections: each Chrome extension instance is one websocket.
        self._connections: set = set()
        self._connections_lock = threading.Lock()
        # Pending reply slots: { msg_id: {"event": threading.Event, "result": Any, "error": str|None} }
        self._pending: dict[str, dict] = {}
        self._pending_lock = threading.Lock()
        self._started = False

    # -----------------------------------------------------------------------
    # Public API (called from Qt main thread)
    # -----------------------------------------------------------------------

    def start(self) -> None:
        """Spawn the background asyncio thread and start the WebSocket server."""
        if self._started:
            return
        self._started = True
        self._thread = threading.Thread(
            target=self._run_loop,
            name="browser-agent-ws",
            daemon=True,
        )
        self._thread.start()
        logger.info(
            "BrowserAgentServer starting on ws://127.0.0.1:%d%s",
            BROWSER_AGENT_PORT,
            BROWSER_AGENT_PATH,
        )

    def stop(self) -> None:
        """Request an orderly shutdown of the asyncio loop."""
        if self._loop is not None and self._loop.is_running():
            self._loop.call_soon_threadsafe(self._loop.stop)

    def connection_count(self) -> int:
        """Return the number of currently connected extension instances."""
        with self._connections_lock:
            return len(self._connections)

    def send_command(self, command: str, **params: Any) -> Any:
        """
        Send a command to all connected extension instances and return the
        first reply received, or raise on timeout or error.

        Blocks the calling thread for up to COMMAND_TIMEOUT_S seconds.
        Safe to call from the Qt main thread (uses threading.Event, not asyncio).

        Raises:
            RuntimeError: if no extension is connected.
            TimeoutError: if the extension does not reply within COMMAND_TIMEOUT_S.
            RuntimeError: if the extension replies with an error payload.
        """
        with self._connections_lock:
            if not self._connections:
                raise RuntimeError("No browser extension is connected.")

        msg_id = uuid.uuid4().hex[:12]
        payload = {"id": msg_id, "command": command, **params}
        slot: dict = {"event": threading.Event(), "result": None, "error": None}

        with self._pending_lock:
            self._pending[msg_id] = slot

        # Schedule the send on the asyncio loop from this (Qt main) thread.
        if self._loop is None or not self._loop.is_running():
            with self._pending_lock:
                self._pending.pop(msg_id, None)
            raise RuntimeError("Browser agent event loop is not running.")

        self._loop.call_soon_threadsafe(
            lambda: asyncio.ensure_future(self._broadcast(payload), loop=self._loop)
        )

        arrived = slot["event"].wait(timeout=COMMAND_TIMEOUT_S)
        with self._pending_lock:
            self._pending.pop(msg_id, None)

        if not arrived:
            raise TimeoutError(
                f"Command '{command}' timed out after {COMMAND_TIMEOUT_S}s "
                f"(id={msg_id})."
            )
        if slot["error"] is not None:
            raise RuntimeError(
                f"Extension returned error for '{command}': {slot['error']}"
            )
        return slot["result"]

    # -----------------------------------------------------------------------
    # Asyncio internals (run on the background thread's event loop)
    # -----------------------------------------------------------------------

    def _run_loop(self) -> None:
        """Entry point for the background daemon thread."""
        self._loop = asyncio.new_event_loop()
        asyncio.set_event_loop(self._loop)
        self._loop.run_until_complete(self._serve())
        self._loop.close()

    async def _serve(self) -> None:
        """Start the WebSocket server and run until the loop is stopped."""
        try:
            from websockets.asyncio.server import serve  # type: ignore[import-untyped]
        except ImportError as exc:
            logger.error(
                "websockets library not found. "
                "Run: pip install 'websockets>=14' -- %s", exc
            )
            return

        async with serve(
            self._handle_connection,
            "127.0.0.1",
            BROWSER_AGENT_PORT,
            logger=logging.getLogger("websockets.server"),
        ) as server:
            self._ws_server = server
            logger.info(
                "BrowserAgentServer listening on ws://127.0.0.1:%d",
                BROWSER_AGENT_PORT,
            )
            await asyncio.get_event_loop().create_future()  # run forever

    async def _handle_connection(self, websocket) -> None:
        """Handle one connected WebSocket client (one browser extension instance).

        websocket is a websockets.asyncio.server.ServerConnection. The request
        path is available at websocket.request.path after the handshake.
        """
        # Path filtering: only accept the designated agent path.
        # websocket.request is available immediately after the handler is called
        # because the handshake has already completed.
        request = getattr(websocket, "request", None)
        path = request.path if request is not None else "/"
        if path != BROWSER_AGENT_PATH:
            logger.warning(
                "BrowserAgentServer: rejected connection on path %r "
                "(expected %r)", path, BROWSER_AGENT_PATH
            )
            await websocket.close(1008, "Wrong path")
            return

        with self._connections_lock:
            self._connections.add(websocket)
        logger.info(
            "Browser extension connected. Active connections: %d",
            self.connection_count(),
        )

        try:
            async for raw in websocket:
                self._on_message_received(raw)
        except Exception as exc:
            logger.debug("BrowserAgentServer: connection closed with error: %s", exc)
        finally:
            with self._connections_lock:
                self._connections.discard(websocket)
            logger.info(
                "Browser extension disconnected. Active connections: %d",
                self.connection_count(),
            )

    async def _broadcast(self, payload: dict) -> None:
        """Send payload to all connected extension instances."""
        raw = json.dumps(payload)
        with self._connections_lock:
            targets = list(self._connections)
        for ws in targets:
            try:
                await ws.send(raw)
                logger.debug("BrowserAgentServer sent: %s", raw)
            except Exception as exc:
                logger.warning("BrowserAgentServer: send failed: %s", exc)

    def _on_message_received(self, raw: str) -> None:
        """Parse an incoming message and resolve any pending reply slot."""
        logger.info("BrowserAgentServer received: %s", raw)
        try:
            msg = json.loads(raw)
        except json.JSONDecodeError as exc:
            logger.warning("BrowserAgentServer: non-JSON message: %r -- %s", raw, exc)
            return

        msg_id = msg.get("id")
        if msg_id is None:
            logger.warning("BrowserAgentServer: message missing 'id': %s", msg)
            return

        with self._pending_lock:
            slot = self._pending.get(msg_id)

        if slot is None:
            # Unsolicited message (extension push or unknown id) -- just log it.
            logger.info("BrowserAgentServer: unsolicited message (id=%s): %s", msg_id, msg)
            return

        if "error" in msg:
            slot["error"] = msg["error"]
        else:
            slot["result"] = msg.get("result")
        slot["event"].set()
